version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-123456}
      POSTGRES_DB: booking_tour
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d booking_tour"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis-cache:
    image: redis:7-alpine
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongodb-nosql:
    image: mongo:6.0
    container_name: mongo-container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: tour_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq-broker:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-container
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  minio-storage:
    image: minio/minio
    container_name: minio-container
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  booking-tour-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-booking-app
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      postgres-db:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:
  mongo_data:
  rabbitmq_data:
  minio_data: